d={}
name=input("Enter friends:")
lang= input("Enter language name:")
d.update({name:lang})
name=input("Enter friends:")
lang= input("Enter language name:")
d.update({name:lang})
name=input("Enter friends:")
lang= input("Enter language name:")
d.update({name:lang})
name=input("Enter friends:")
lang= input("Enter language name:")
d.update({name:lang})
name=input("Enter friends:")
lang= input("Enter language name:")
d.update({name:lang})
print(d)